In [1]:
import pandas as pd
from my_example import obj_ic_fundacoes, tensao_adm_solo
from metapy_toolbox import metaheuristic_optimizer

In [2]:
df_aux = pd.read_excel('planilha_padrao.xlsx', header=[0,1])
df_aux

            Elemento combinação 1         combinação 2         combinação 3  \
  Unnamed: 0_level_1           Fz  Mx  My           Fz  Mx  My           Fz
0                 P1           10  10  10           20   3  20          100
1                 P2           10  10  10           20  20  20          100
2                 P3           10  10  10           20  20  20          100
3                 P4           10  10  10           20  20  20          100
4                 P5           10  10  10           20  20  20          100
5                 P6           10  10  10           20  20  20          100
6                 P7           10  10  10           20  20  20          100
7                 P8           10  10  10           20  20  20          100
8                 P9           10  10  10           20  20  20          100
9                P10           10  10  10           20  20  20          100

           ... combinação 7 combinação 8       combinação 9        \
    Mx My  ...           My           Fz Mx My           Fz Mx My
0  100  1  ...            1            1  1  1            1  1  1
1  100  1  ...            1            1  1  1            1  1  1
2  100  1  ...            1            1  1  1            1  1  1
3  100  1  ...            1            1  1  1            1  1  1
4  100  1  ...            1            1  1  1            1  1  1
5  100  1  ...            1            1  1  1            1  1  1
6  100  1  ...            1            1  1  1            1  1  1
7  100  1  ...            1            1  1  1            1  1  1
8  100  1  ...            1            1  1  1            1  1  1
9  100  1  ...            1            1  1  1            1  1  1

  combinação 10
             Fz Mx My
0             1  1  1
1             1  1  1
2             1  1  1
3             1  1  1
4             1  1  1
5             1  1  1
6             1  1  1
7             1  1  1
8             1  1  1
9             1  1  1

[10 rows x 31 columns]

In [3]:
spt = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
tipo_solo = ["argila", "silte", "pedregulho", "areia", "argila", "silte", "pedregulho", "areia", "argila", "silte"]
xg = [0, 10, 20, 30, 40, 0, 10, 20, 30, 40]
yg = [0, 10, 20, 30, 40, 0, 10, 20, 30, 40]


df_aux.insert(1, 'spt', spt[:len(df_aux)])
df_aux.insert(2, 'solo', tipo_solo[:len(df_aux)])
df_aux.insert(3, 'xg (m)', xg[:len(df_aux)])
df_aux.insert(4, 'yg (m)', yg[:len(df_aux)])
df_aux

            Elemento spt        solo xg (m) yg (m) combinação 1          \
  Unnamed: 0_level_1                                         Fz  Mx  My
0                 P1  10      argila      0      0           10  10  10
1                 P2  20       silte     10     10           10  10  10
2                 P3  30  pedregulho     20     20           10  10  10
3                 P4  40       areia     30     30           10  10  10
4                 P5  50      argila     40     40           10  10  10
5                 P6  10       silte      0      0           10  10  10
6                 P7  20  pedregulho     10     10           10  10  10
7                 P8  30       areia     20     20           10  10  10
8                 P9  40      argila     30     30           10  10  10
9                P10  50       silte     40     40           10  10  10

  combinação 2      ... combinação 7 combinação 8       combinação 9        \
            Fz  Mx  ...           My           Fz Mx My           Fz Mx My
0           20   3  ...            1            1  1  1            1  1  1
1           20  20  ...            1            1  1  1            1  1  1
2           20  20  ...            1            1  1  1            1  1  1
3           20  20  ...            1            1  1  1            1  1  1
4           20  20  ...            1            1  1  1            1  1  1
5           20  20  ...            1            1  1  1            1  1  1
6           20  20  ...            1            1  1  1            1  1  1
7           20  20  ...            1            1  1  1            1  1  1
8           20  20  ...            1            1  1  1            1  1  1
9           20  20  ...            1            1  1  1            1  1  1

  combinação 10
             Fz Mx My
0             1  1  1
1             1  1  1
2             1  1  1
3             1  1  1
4             1  1  1
5             1  1  1
6             1  1  1
7             1  1  1
8             1  1  1
9             1  1  1

[10 rows x 35 columns]

In [4]:
df = tensao_adm_solo(df_aux)
df

            Elemento spt        solo xg (m) yg (m) combinação 1          \
  Unnamed: 0_level_1                                         Fz  Mx  My
0                 P1  10      argila      0      0           10  10  10
1                 P2  20       silte     10     10           10  10  10
2                 P3  30  pedregulho     20     20           10  10  10
3                 P4  40       areia     30     30           10  10  10
4                 P5  50      argila     40     40           10  10  10
5                 P6  10       silte      0      0           10  10  10
6                 P7  20  pedregulho     10     10           10  10  10
7                 P8  30       areia     20     20           10  10  10
8                 P9  40      argila     30     30           10  10  10
9                P10  50       silte     40     40           10  10  10

  combinação 2      ... combinação 8       combinação 9       combinação 10  \
            Fz  Mx  ...           Fz Mx My           Fz Mx My            Fz
0           20   3  ...            1  1  1            1  1  1             1
1           20  20  ...            1  1  1            1  1  1             1
2           20  20  ...            1  1  1            1  1  1             1
3           20  20  ...            1  1  1            1  1  1             1
4           20  20  ...            1  1  1            1  1  1             1
5           20  20  ...            1  1  1            1  1  1             1
6           20  20  ...            1  1  1            1  1  1             1
7           20  20  ...            1  1  1            1  1  1             1
8           20  20  ...            1  1  1            1  1  1             1
9           20  20  ...            1  1  1            1  1  1             1

        sigma_adm (kPa)
  Mx My
0  1  1      200.000000
1  1  1      400.000000
2  1  1     1000.000000
3  1  1     1000.000000
4  1  1     1000.000000
5  1  1      200.000000
6  1  1      666.666667
7  1  1      750.000000
8  1  1      800.000000
9  1  1     1000.000000

[10 rows x 36 columns]

In [5]:
def data_comb(planilha, df, combinacoes):
    """
    Gera combinações 3 a 3 das colunas de uma planilha com header duplo,
    filtrando por combinações específicas fornecidas em um dicionário,
    e retorna uma lista de dicionários no formato desejado.

    Parâmetros:
    - planilha: Caminho para o arquivo Excel com header duplo.
    - combinacoes: Dicionário com combinações desejadas no formato 
      {'combinação 1': ['Fz', 'Mx', 'My'], ...}

    Retorno:
    - Uma lista de dicionários contendo os valores das combinações.
    """
    # df = pd.read_excel(planilha, header=[0, 1])

    lista_resultados = []
    for _, row in df.iterrows():
        resultado_linha = {}
        for nome_combinacao, colunas_desejadas in combinacoes.items():
            colunas_multiindex = [(nome_combinacao, coluna) for coluna in colunas_desejadas]
            if all(coluna in df.columns for coluna in colunas_multiindex):
                valores = row[colunas_multiindex].tolist()
                resultado_linha[nome_combinacao] = valores
            else:
                print(f"A combinação {colunas_desejadas} não está disponível para {nome_combinacao}.")
        
        lista_resultados.append(resultado_linha)

    return lista_resultados

combinacoes = {
    'combinação 1': ['Fz', 'Mx', 'My'],
    'combinação 2': ['Fz', 'Mx', 'My'],
    'combinação 3': ['Fz', 'Mx', 'My']
}

lista_comb = data_comb("planilha_padrao.xlsx", df_aux, combinacoes)
lista_comb

[{'combinação 1': [10, 10, 10],
  'combinação 2': [20, 3, 20],
  'combinação 3': [100, 100, 1]},
 {'combinação 1': [10, 10, 10],
  'combinação 2': [20, 20, 20],
  'combinação 3': [100, 100, 1]},
 {'combinação 1': [10, 10, 10],
  'combinação 2': [20, 20, 20],
  'combinação 3': [100, 100, 1]},
 {'combinação 1': [10, 10, 10],
  'combinação 2': [20, 20, 20],
  'combinação 3': [100, 100, 1]},
 {'combinação 1': [10, 10, 10],
  'combinação 2': [20, 20, 20],
  'combinação 3': [100, 100, 1]},
 {'combinação 1': [10, 10, 10],
  'combinação 2': [20, 20, 20],
  'combinação 3': [100, 100, 1]},
 {'combinação 1': [10, 10, 10],
  'combinação 2': [20, 20, 20],
  'combinação 3': [100, 100, 1]},
 {'combinação 1': [10, 10, 10],
  'combinação 2': [20, 20, 20],
  'combinação 3': [100, 100, 1]},
 {'combinação 1': [10, 10, 10],
  'combinação 2': [20, 20, 20],
  'combinação 3': [100, 100, 1]},
 {'combinação 1': [10, 10, 10],
  'combinação 2': [20, 20, 20],
  'combinação 3': [100, 100, 1]}]

In [6]:
dim_a = []
dim_b = []
df
for i, row in df.iterrows():
        # Recolhendo os dados do pilar
        dados_fundacao = { 
                                'combinações': lista_comb[i],
                                'sigma_adm (kPa)': row[('sigma_adm (kPa)', '')],
                         }
        # Otimização
        algorithm_setup = {   
                'number of iterations': 100,
                'number of population': 5,
                'number of dimensions': 2,
                'x pop lower limit': [0.60, 0.60], # 0.60
                'x pop upper limit': [2.25, 2.25],
                'none variable': dados_fundacao,
                'objective function': obj_ic_fundacoes,
                'algorithm parameters': {
                                        'selection': {'type': 'roulette'},
                                        'crossover': {'crossover rate (%)': 82, 'type':'linear'},
                                        'mutation': {'mutation rate (%)': 12, 'type': 'hill climbing', 'cov (%)': 15, 'pdf': 'gaussian'},
                                        }
                }
        n_rep = 5
        general_setup = {   
                'number of repetitions': n_rep,
                'type code': 'real code',
                'initial pop. seed': [None] * n_rep,
                'algorithm': 'genetic_algorithm_01',
                }
        df_all_reps, df_resume_all_reps, reports, status = metaheuristic_optimizer(algorithm_setup, general_setup)
        df_novo = df_resume_all_reps[status]
        dimensoes_sapata_a = list(df_novo['X_0_BEST'])[-1]
        dimensoes_sapata_b = list(df_novo['X_1_BEST'])[-1]
        dim_a.append(dimensoes_sapata_a)
        dim_b.append(dimensoes_sapata_b)

# Atribuição da dimensão otimizada
df['dimensão a (m)'] = dim_a
df['dimensão b (m)'] = dim_b

 Optimization results:

 - Best repetition id:    2
 - Best of:               1.1216642371e+00
 - Design variables:      [2.25, 0.8308623978653764]
 - Process time (s):      2.271527
 - Best process time (s): 0.003301

 Optimization results:

 - Best repetition id:    0
 - Best of:               6.5765758710e-01
 - Design variables:      [1.8268266308364867, 0.6]
 - Process time (s):      2.291352
 - Best process time (s): 0.002013

 Optimization results:

 - Best repetition id:    2
 - Best of:               3.9450933598e-01
 - Design variables:      [1.0958592666084197, 0.6]
 - Process time (s):      2.315151
 - Best process time (s): 0.002145

 Optimization results:

 - Best repetition id:    0
 - Best of:               3.9450933598e-01
 - Design variables:      [1.0958592666084197, 0.6]
 - Process time (s):      2.324641
 - Best process time (s): 0.002112

 Optimization results:

 - Best repetition id:    1
 - Best of:               3.9450933598e-01
 - Design variables:      [1.0958592666084197, 0.6]
 - Process time (s):      2.400160
 - Best process time (s): 0.003009

 Optimization results:

 - Best repetition id:    0
 - Best of:               1.1216642371e+00
 - Design variables:      [2.25, 0.8308623978653764]
 - Process time (s):      2.303814
 - Best process time (s): 0.003000

 Optimization results:

 - Best repetition id:    0
 - Best of:               4.9317809277e-01
 - Design variables:      [1.3699391465707342, 0.6]
 - Process time (s):      2.265656
 - Best process time (s): 0.001998

 Optimization results:

 - Best repetition id:    2
 - Best of:               4.6201435382e-01
 - Design variables:      [1.2833732050570437, 0.6]
 - Process time (s):      2.363735
 - Best process time (s): 0.003007

 Optimization results:

 - Best repetition id:    0
 - Best of:               4.4585049740e-01
 - Design variables:      [1.238473603901496, 0.6]
 - Process time (s):      2.433192
 - Best process time (s): 0.002010

 Optimization results:

 - Best repetition id:    0
 - Best of:               3.9450933598e-01
 - Design variables:      [1.0958592666084197, 0.6]
 - Process time (s):      2.332210
 - Best process time (s): 0.003001

In [8]:
df = df[[col for col in df.columns if not col[0].startswith("combinação")]]
df.columns = df.columns.get_level_values(0)
df

,Elemento,spt,solo,xg (m),yg (m),sigma_adm (kPa),dimensão a (m),dimensão b (m)
0,P1,10,argila,0,0,200.000000,2.250000,0.830862
1,P2,20,silte,10,10,400.000000,1.826827,0.600000
2,P3,30,pedregulho,20,20,1000.000000,1.095859,0.600000
3,P4,40,areia,30,30,1000.000000,1.095859,0.600000
4,P5,50,argila,40,40,1000.000000,1.095859,0.600000
5,P6,10,silte,0,0,200.000000,2.250000,0.830862
6,P7,20,pedregulho,10,10,666.666667,1.369939,0.600000
7,P8,30,areia,20,20,750.000000,1.283373,0.600000
8,P9,40,argila,30,30,800.000000,1.238474,0.600000
9,P10,50,silte,40,40,1000.000000,1.095859,0.600000