In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_excel('planilha_padrao.xlsx', header=[0,1])
df

            Elemento combinação 1         combinação 2         combinação 3  \
  Unnamed: 0_level_1           Fz  Mx  My           Fz  Mx  My           Fz
0                 P1           10  10  10           20  20  20          100
1                 P2           10  10  10           20  20  20          100
2                 P3           10  10  10           20  20  20          100
3                 P4           10  10  10           20  20  20          100
4                 P5           10  10  10           20  20  20          100
5                 P6           10  10  10           20  20  20          100
6                 P7           10  10  10           20  20  20          100
7                 P8           10  10  10           20  20  20          100
8                 P9           10  10  10           20  20  20          100
9                P10           10  10  10           20  20  20          100

             ... combinação 7 combinação 8       combinação 9        \
    Mx   My  ...           My           Fz Mx My           Fz Mx My
0  100  100  ...            1            1  1  1            1  1  1
1  100  100  ...            1            1  1  1            1  1  1
2  100  100  ...            1            1  1  1            1  1  1
3  100  100  ...            1            1  1  1            1  1  1
4  100  100  ...            1            1  1  1            1  1  1
5  100  100  ...            1            1  1  1            1  1  1
6  100  100  ...            1            1  1  1            1  1  1
7  100  100  ...            1            1  1  1            1  1  1
8  100  100  ...            1            1  1  1            1  1  1
9  100  100  ...            1            1  1  1            1  1  1

  combinação 10
             Fz Mx My
0             1  1  1
1             1  1  1
2             1  1  1
3             1  1  1
4             1  1  1
5             1  1  1
6             1  1  1
7             1  1  1
8             1  1  1
9             1  1  1

[10 rows x 31 columns]

In [3]:
spt = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
tipo_solo = ['Arenoso', 'Argiloso', 'Siltoso', 'Mistura', 'Arenoso', 'Argiloso', 'Siltoso', 'Mistura', 'Arenoso', 'Argiloso']
xg = [0, 10, 20, 30, 40, 0, 10, 20, 30, 40]
yg = [0, 10, 20, 30, 40, 0, 10, 20, 30, 40]


df.insert(1, 'SPT', spt[:len(df)])
df.insert(2, 'Tipo de Solo', tipo_solo[:len(df)])
df.insert(3, 'Xg', xg[:len(df)])
df.insert(4, 'Yg', yg[:len(df)])
df.to_excel('planilha_padrao_atualizada.xlsx')

In [6]:
import pandas as pd
from itertools import combinations

def combinar_dados(planilha, combinacoes):
    """
    Gera combinações 3 a 3 das colunas de uma planilha com header duplo,
    filtrando por combinações específicas fornecidas em um dicionário.

    Parâmetros:
    - planilha: Caminho para o arquivo Excel com header duplo.
    - combinacoes: Dicionário com combinações desejadas no formato 
      {'combinação 1': ['Fz', 'Mx', 'My'], ...}

    Retorno:
    - Um DataFrame contendo as combinações filtradas.
    """
    # Carregar a planilha Excel com cabeçalho duplo
    df = pd.read_excel(planilha, header=[0, 1])

    # Resultado final
    resultados = {}

    # Iterar sobre as combinações desejadas
    for nome_combinacao, colunas_desejadas in combinacoes.items():
        # Verificar se as colunas desejadas existem no MultiIndex
        colunas_multiindex = [(nome_combinacao, coluna) for coluna in colunas_desejadas]
        if all(coluna in df.columns for coluna in colunas_multiindex):
            # Filtrar as colunas desejadas
            resultados[nome_combinacao] = df[colunas_multiindex]
        else:
            print(f"A combinação {colunas_desejadas} não está disponível para {nome_combinacao}.")

    # Combinar todas as combinações em um único DataFrame
    df_combinado = pd.concat(resultados, axis=1)
    return df_combinado

# Exemplo de uso
combinacoes = {
    'combinação 1': ['Fz', 'My', 'My'],  # Substituir pelos nomes reais do nível inferior
    'combinação 3': ['Fz', 'Mx', 'My'],  # Pode repetir combinações
}

# Substituir "sua_planilha.xlsx" pelo caminho correto
resultado = combinar_dados("planilha_padrao.xlsx", combinacoes)
resultado

  combinação 1         combinação 3
  combinação 1         combinação 3
            Fz  My  My           Fz   Mx   My
0           10  10  10          100  100  100
1           10  10  10          100  100  100
2           10  10  10          100  100  100
3           10  10  10          100  100  100
4           10  10  10          100  100  100
5           10  10  10          100  100  100
6           10  10  10          100  100  100
7           10  10  10          100  100  100
8           10  10  10          100  100  100
9           10  10  10          100  100  100